// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamemessage.proto

package org.tont.proto;

public final class GameMessage {
  private GameMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.PlayerRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 msg_type = 1;</code>
     */
    int getMsgType();
  }
  /**
   * Protobuf type {@code proto.PlayerRequest}
   *
   * <pre>
   * [START messages]
   * </pre>
   */
  public  static final class PlayerRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.PlayerRequest)
      PlayerRequestOrBuilder {
    // Use PlayerRequest.newBuilder() to construct.
    private PlayerRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerRequest() {
      msgType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PlayerRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              msgType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.tont.proto.GameMessage.PlayerRequest.class, org.tont.proto.GameMessage.PlayerRequest.Builder.class);
    }

    public interface PlayerAccountInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.PlayerRequest.PlayerAccountInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 player_id = 1;</code>
       */
      int getPlayerId();

      /**
       * <code>optional string token = 2;</code>
       */
      java.lang.String getToken();
      /**
       * <code>optional string token = 2;</code>
       */
      com.google.protobuf.ByteString
          getTokenBytes();

      /**
       * <code>optional string player_account = 3;</code>
       */
      java.lang.String getPlayerAccount();
      /**
       * <code>optional string player_account = 3;</code>
       */
      com.google.protobuf.ByteString
          getPlayerAccountBytes();

      /**
       * <code>optional string player_password = 4;</code>
       */
      java.lang.String getPlayerPassword();
      /**
       * <code>optional string player_password = 4;</code>
       */
      com.google.protobuf.ByteString
          getPlayerPasswordBytes();
    }
    /**
     * Protobuf type {@code proto.PlayerRequest.PlayerAccountInfo}
     */
    public  static final class PlayerAccountInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.PlayerRequest.PlayerAccountInfo)
        PlayerAccountInfoOrBuilder {
      // Use PlayerAccountInfo.newBuilder() to construct.
      private PlayerAccountInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private PlayerAccountInfo() {
        playerId_ = 0;
        token_ = "";
        playerAccount_ = "";
        playerPassword_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private PlayerAccountInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                playerId_ = input.readInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                token_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                playerAccount_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                playerPassword_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerAccountInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.class, org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.Builder.class);
      }

      public static final int PLAYER_ID_FIELD_NUMBER = 1;
      private int playerId_;
      /**
       * <code>optional int32 player_id = 1;</code>
       */
      public int getPlayerId() {
        return playerId_;
      }

      public static final int TOKEN_FIELD_NUMBER = 2;
      private volatile java.lang.Object token_;
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PLAYER_ACCOUNT_FIELD_NUMBER = 3;
      private volatile java.lang.Object playerAccount_;
      /**
       * <code>optional string player_account = 3;</code>
       */
      public java.lang.String getPlayerAccount() {
        java.lang.Object ref = playerAccount_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerAccount_ = s;
          return s;
        }
      }
      /**
       * <code>optional string player_account = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerAccountBytes() {
        java.lang.Object ref = playerAccount_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerAccount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PLAYER_PASSWORD_FIELD_NUMBER = 4;
      private volatile java.lang.Object playerPassword_;
      /**
       * <code>optional string player_password = 4;</code>
       */
      public java.lang.String getPlayerPassword() {
        java.lang.Object ref = playerPassword_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerPassword_ = s;
          return s;
        }
      }
      /**
       * <code>optional string player_password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerPasswordBytes() {
        java.lang.Object ref = playerPassword_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (playerId_ != 0) {
          output.writeInt32(1, playerId_);
        }
        if (!getTokenBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, token_);
        }
        if (!getPlayerAccountBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessage.writeString(output, 3, playerAccount_);
        }
        if (!getPlayerPasswordBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessage.writeString(output, 4, playerPassword_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (playerId_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, playerId_);
        }
        if (!getTokenBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, token_);
        }
        if (!getPlayerAccountBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(3, playerAccount_);
        }
        if (!getPlayerPasswordBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(4, playerPassword_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.PlayerRequest.PlayerAccountInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.PlayerRequest.PlayerAccountInfo)
          org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerAccountInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.class, org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.Builder.class);
        }

        // Construct using org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          playerId_ = 0;

          token_ = "";

          playerAccount_ = "";

          playerPassword_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor;
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo getDefaultInstanceForType() {
          return org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.getDefaultInstance();
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo build() {
          org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo buildPartial() {
          org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo result = new org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo(this);
          result.playerId_ = playerId_;
          result.token_ = token_;
          result.playerAccount_ = playerAccount_;
          result.playerPassword_ = playerPassword_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo) {
            return mergeFrom((org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo other) {
          if (other == org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo.getDefaultInstance()) return this;
          if (other.getPlayerId() != 0) {
            setPlayerId(other.getPlayerId());
          }
          if (!other.getToken().isEmpty()) {
            token_ = other.token_;
            onChanged();
          }
          if (!other.getPlayerAccount().isEmpty()) {
            playerAccount_ = other.playerAccount_;
            onChanged();
          }
          if (!other.getPlayerPassword().isEmpty()) {
            playerPassword_ = other.playerPassword_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int playerId_ ;
        /**
         * <code>optional int32 player_id = 1;</code>
         */
        public int getPlayerId() {
          return playerId_;
        }
        /**
         * <code>optional int32 player_id = 1;</code>
         */
        public Builder setPlayerId(int value) {
          
          playerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 player_id = 1;</code>
         */
        public Builder clearPlayerId() {
          
          playerId_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object token_ = "";
        /**
         * <code>optional string token = 2;</code>
         */
        public java.lang.String getToken() {
          java.lang.Object ref = token_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            token_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTokenBytes() {
          java.lang.Object ref = token_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            token_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder setToken(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          token_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder clearToken() {
          
          token_ = getDefaultInstance().getToken();
          onChanged();
          return this;
        }
        /**
         * <code>optional string token = 2;</code>
         */
        public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          token_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object playerAccount_ = "";
        /**
         * <code>optional string player_account = 3;</code>
         */
        public java.lang.String getPlayerAccount() {
          java.lang.Object ref = playerAccount_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            playerAccount_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string player_account = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPlayerAccountBytes() {
          java.lang.Object ref = playerAccount_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            playerAccount_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string player_account = 3;</code>
         */
        public Builder setPlayerAccount(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          playerAccount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string player_account = 3;</code>
         */
        public Builder clearPlayerAccount() {
          
          playerAccount_ = getDefaultInstance().getPlayerAccount();
          onChanged();
          return this;
        }
        /**
         * <code>optional string player_account = 3;</code>
         */
        public Builder setPlayerAccountBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          playerAccount_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object playerPassword_ = "";
        /**
         * <code>optional string player_password = 4;</code>
         */
        public java.lang.String getPlayerPassword() {
          java.lang.Object ref = playerPassword_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            playerPassword_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string player_password = 4;</code>
         */
        public com.google.protobuf.ByteString
            getPlayerPasswordBytes() {
          java.lang.Object ref = playerPassword_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            playerPassword_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string player_password = 4;</code>
         */
        public Builder setPlayerPassword(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          playerPassword_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string player_password = 4;</code>
         */
        public Builder clearPlayerPassword() {
          
          playerPassword_ = getDefaultInstance().getPlayerPassword();
          onChanged();
          return this;
        }
        /**
         * <code>optional string player_password = 4;</code>
         */
        public Builder setPlayerPasswordBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          playerPassword_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:proto.PlayerRequest.PlayerAccountInfo)
      }

      // @@protoc_insertion_point(class_scope:proto.PlayerRequest.PlayerAccountInfo)
      private static final org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo();
      }

      public static org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PlayerAccountInfo>
          PARSER = new com.google.protobuf.AbstractParser<PlayerAccountInfo>() {
        public PlayerAccountInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new PlayerAccountInfo(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<PlayerAccountInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PlayerAccountInfo> getParserForType() {
        return PARSER;
      }

      public org.tont.proto.GameMessage.PlayerRequest.PlayerAccountInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface PlayerGameInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.PlayerRequest.PlayerGameInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 player_nickname = 1;</code>
       */
      int getPlayerNickname();

      /**
       * <code>optional int32 player_level = 2;</code>
       */
      int getPlayerLevel();
    }
    /**
     * Protobuf type {@code proto.PlayerRequest.PlayerGameInfo}
     */
    public  static final class PlayerGameInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:proto.PlayerRequest.PlayerGameInfo)
        PlayerGameInfoOrBuilder {
      // Use PlayerGameInfo.newBuilder() to construct.
      private PlayerGameInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private PlayerGameInfo() {
        playerNickname_ = 0;
        playerLevel_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private PlayerGameInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                playerNickname_ = input.readInt32();
                break;
              }
              case 16: {

                playerLevel_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerGameInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.class, org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.Builder.class);
      }

      public static final int PLAYER_NICKNAME_FIELD_NUMBER = 1;
      private int playerNickname_;
      /**
       * <code>optional int32 player_nickname = 1;</code>
       */
      public int getPlayerNickname() {
        return playerNickname_;
      }

      public static final int PLAYER_LEVEL_FIELD_NUMBER = 2;
      private int playerLevel_;
      /**
       * <code>optional int32 player_level = 2;</code>
       */
      public int getPlayerLevel() {
        return playerLevel_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (playerNickname_ != 0) {
          output.writeInt32(1, playerNickname_);
        }
        if (playerLevel_ != 0) {
          output.writeInt32(2, playerLevel_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (playerNickname_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, playerNickname_);
        }
        if (playerLevel_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, playerLevel_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.PlayerRequest.PlayerGameInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:proto.PlayerRequest.PlayerGameInfo)
          org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerGameInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.class, org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.Builder.class);
        }

        // Construct using org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          playerNickname_ = 0;

          playerLevel_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor;
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo getDefaultInstanceForType() {
          return org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.getDefaultInstance();
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo build() {
          org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo buildPartial() {
          org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo result = new org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo(this);
          result.playerNickname_ = playerNickname_;
          result.playerLevel_ = playerLevel_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo) {
            return mergeFrom((org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo other) {
          if (other == org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo.getDefaultInstance()) return this;
          if (other.getPlayerNickname() != 0) {
            setPlayerNickname(other.getPlayerNickname());
          }
          if (other.getPlayerLevel() != 0) {
            setPlayerLevel(other.getPlayerLevel());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int playerNickname_ ;
        /**
         * <code>optional int32 player_nickname = 1;</code>
         */
        public int getPlayerNickname() {
          return playerNickname_;
        }
        /**
         * <code>optional int32 player_nickname = 1;</code>
         */
        public Builder setPlayerNickname(int value) {
          
          playerNickname_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 player_nickname = 1;</code>
         */
        public Builder clearPlayerNickname() {
          
          playerNickname_ = 0;
          onChanged();
          return this;
        }

        private int playerLevel_ ;
        /**
         * <code>optional int32 player_level = 2;</code>
         */
        public int getPlayerLevel() {
          return playerLevel_;
        }
        /**
         * <code>optional int32 player_level = 2;</code>
         */
        public Builder setPlayerLevel(int value) {
          
          playerLevel_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 player_level = 2;</code>
         */
        public Builder clearPlayerLevel() {
          
          playerLevel_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:proto.PlayerRequest.PlayerGameInfo)
      }

      // @@protoc_insertion_point(class_scope:proto.PlayerRequest.PlayerGameInfo)
      private static final org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo();
      }

      public static org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PlayerGameInfo>
          PARSER = new com.google.protobuf.AbstractParser<PlayerGameInfo>() {
        public PlayerGameInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new PlayerGameInfo(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<PlayerGameInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PlayerGameInfo> getParserForType() {
        return PARSER;
      }

      public org.tont.proto.GameMessage.PlayerRequest.PlayerGameInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>optional int32 msg_type = 1;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgType_ != 0) {
        output.writeInt32(1, msgType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.tont.proto.GameMessage.PlayerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.tont.proto.GameMessage.PlayerRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.PlayerRequest}
     *
     * <pre>
     * [START messages]
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.PlayerRequest)
        org.tont.proto.GameMessage.PlayerRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.tont.proto.GameMessage.PlayerRequest.class, org.tont.proto.GameMessage.PlayerRequest.Builder.class);
      }

      // Construct using org.tont.proto.GameMessage.PlayerRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.tont.proto.GameMessage.internal_static_proto_PlayerRequest_descriptor;
      }

      public org.tont.proto.GameMessage.PlayerRequest getDefaultInstanceForType() {
        return org.tont.proto.GameMessage.PlayerRequest.getDefaultInstance();
      }

      public org.tont.proto.GameMessage.PlayerRequest build() {
        org.tont.proto.GameMessage.PlayerRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.tont.proto.GameMessage.PlayerRequest buildPartial() {
        org.tont.proto.GameMessage.PlayerRequest result = new org.tont.proto.GameMessage.PlayerRequest(this);
        result.msgType_ = msgType_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.tont.proto.GameMessage.PlayerRequest) {
          return mergeFrom((org.tont.proto.GameMessage.PlayerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.tont.proto.GameMessage.PlayerRequest other) {
        if (other == org.tont.proto.GameMessage.PlayerRequest.getDefaultInstance()) return this;
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.tont.proto.GameMessage.PlayerRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.tont.proto.GameMessage.PlayerRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgType_ ;
      /**
       * <code>optional int32 msg_type = 1;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional int32 msg_type = 1;</code>
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msg_type = 1;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.PlayerRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.PlayerRequest)
    private static final org.tont.proto.GameMessage.PlayerRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.tont.proto.GameMessage.PlayerRequest();
    }

    public static org.tont.proto.GameMessage.PlayerRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlayerRequest>() {
      public PlayerRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PlayerRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PlayerRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerRequest> getParserForType() {
      return PARSER;
    }

    public org.tont.proto.GameMessage.PlayerRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PlayerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PlayerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PlayerRequest_PlayerAccountInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_PlayerRequest_PlayerGameInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gamemessage.proto\022\005proto\"\312\001\n\rPlayerReq" +
      "uest\022\020\n\010msg_type\030\001 \001(\005\032f\n\021PlayerAccountI" +
      "nfo\022\021\n\tplayer_id\030\001 \001(\005\022\r\n\005token\030\002 \001(\t\022\026\n" +
      "\016player_account\030\003 \001(\t\022\027\n\017player_password" +
      "\030\004 \001(\t\032?\n\016PlayerGameInfo\022\027\n\017player_nickn" +
      "ame\030\001 \001(\005\022\024\n\014player_level\030\002 \001(\005B@\n\016org.t" +
      "ont.protoB\013GameMessage\252\002 Google.Protobuf" +
      ".ToNT.GameMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_PlayerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PlayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PlayerRequest_descriptor,
        new java.lang.String[] { "MsgType", });
    internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor =
      internal_static_proto_PlayerRequest_descriptor.getNestedTypes().get(0);
    internal_static_proto_PlayerRequest_PlayerAccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PlayerRequest_PlayerAccountInfo_descriptor,
        new java.lang.String[] { "PlayerId", "Token", "PlayerAccount", "PlayerPassword", });
    internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor =
      internal_static_proto_PlayerRequest_descriptor.getNestedTypes().get(1);
    internal_static_proto_PlayerRequest_PlayerGameInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_PlayerRequest_PlayerGameInfo_descriptor,
        new java.lang.String[] { "PlayerNickname", "PlayerLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
